insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Buddie', 'McKew', 'Active', '6/30/2022', '4/8/2023', 'Services');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Don', 'Houtby', 'Active', '10/7/2023', '11/11/2020', 'Sales');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Nickolaus', 'Matuszewski', 'Inactive', '1/23/2023', '1/14/2022', 'Services');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Priscilla', 'Brownstein', 'Active', '6/14/2022', '4/1/2021', 'Product Management');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Raina', 'Glaves', 'Active', '10/29/2022', '2/26/2023', 'Support');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Cullen', 'Shirley', 'Inactive', '9/12/2022', '8/18/2023', 'Product Management');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Pollyanna', 'Andreucci', 'Inactive', '9/6/2023', '1/28/2022', 'Services');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Mufi', 'Cromblehome', 'Inactive', '10/7/2023', '7/18/2020', 'Services');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Imelda', 'Gloucester', 'Active', '10/18/2022', '3/1/2023', 'Support');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Frants', 'Pendrich', 'Active', '11/11/2022', '2/2/2023', 'Marketing');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Gabrila', 'McGuigan', 'Active', '8/5/2022', '10/19/2020', 'Support');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Laverne', 'Ryles', 'Active', '7/21/2023', '9/21/2021', 'Marketing');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Abbi', 'Garnsworthy', 'Inactive', '10/5/2023', '9/1/2021', 'Business Development');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Wrennie', 'Klyn', 'Active', '9/8/2023', '6/11/2022', 'Sales');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Genovera', 'Patel', 'Inactive', '11/8/2022', '8/2/2023', 'Human Resources');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Allister', 'Swinburne', 'Active', '7/27/2023', '9/24/2023', 'Business Development');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Almeta', 'Tofanini', 'Active', '11/23/2022', '12/12/2021', 'Business Development');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Bendix', 'Fibbings', 'Active', '10/9/2023', '10/27/2022', 'Business Development');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Rhys', 'Whitmell', 'Inactive', '4/17/2023', '6/16/2022', 'Sales');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Maggie', 'Denty', 'Active', '6/27/2023', '8/17/2023', 'Sales');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Shea', 'Audus', 'Active', '10/4/2023', '11/15/2023', 'Engineering');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Allin', 'Leall', 'Inactive', '10/8/2023', '5/8/2023', 'Product Management');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Richardo', 'Bonsul', 'Active', '10/27/2023', '8/19/2020', 'Support');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Bobby', 'Woofenden', 'Active', '4/6/2023', '8/3/2022', 'Support');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Twila', 'de Mendoza', 'Inactive', '12/26/2022', '10/1/2022', 'Business Development');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Gertrude', 'Splevings', 'Inactive', '2/2/2023', '9/24/2022', 'Product Management');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Otha', 'Tonkinson', 'Active', '3/8/2023', '4/1/2023', 'Support');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Mychal', 'Boynes', 'Active', '3/11/2023', '3/18/2022', 'Services');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Marena', 'Coppock.', 'Active', '6/4/2022', '6/8/2020', 'Accounting');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Jocelyn', 'Haldin', 'Inactive', '9/12/2023', '8/20/2023', 'Marketing');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Keely', 'MacKimmie', 'Active', '12/24/2022', '7/11/2020', 'Engineering');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Ana', 'Fliege', 'Inactive', '11/20/2022', '8/25/2023', 'Support');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Grayce', 'McKearnen', 'Inactive', '10/8/2022', '7/5/2022', 'Sales');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Lazaro', 'Taill', 'Inactive', '4/22/2023', '10/28/2023', 'Product Management');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Jacquelynn', 'Tinson', 'Active', '2/27/2023', '7/3/2020', 'Sales');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Tess', 'Greatrakes', 'Inactive', '4/25/2023', '7/7/2023', 'Training');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Nadya', 'Jeandot', 'Active', '7/23/2022', '8/20/2021', 'Support');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Murdoch', 'Bairstow', 'Active', '9/5/2023', '9/2/2023', 'Sales');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Findley', 'Middlemist', 'Inactive', '1/29/2023', '4/1/2022', 'Product Management');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Dale', 'Grinyov', 'Inactive', '1/28/2023', '5/25/2023', 'Research and Development');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Jelene', 'Corinton', 'Inactive', '7/5/2022', '2/19/2021', 'Legal');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Cynde', 'Osburn', 'Inactive', '10/25/2023', '4/25/2022', 'Training');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Elizabeth', 'Ryder', 'Active', '6/16/2022', '4/16/2022', 'Product Management');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Chico', 'Morratt', 'Inactive', '7/14/2022', '7/1/2023', 'Support');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Beatriz', 'Sartain', 'Active', '8/17/2023', '11/2/2020', 'Services');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Ania', 'Driussi', 'Active', '10/26/2023', '7/28/2023', 'Training');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Mead', 'Romanet', 'Active', '11/30/2023', '6/28/2023', 'Accounting');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Koral', 'Tunn', 'Active', '4/26/2023', '5/31/2023', 'Marketing');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Stuart', 'Maddison', 'Active', '6/27/2023', '10/12/2022', 'Marketing');
insert into EMPLOYEE (FirstName, LastName, Status, DateActive, DateInactive, department) values ('Scarface', 'Painter', 'Active', '8/6/2023', '1/25/2021', 'Research and Development');
